[application]
name = "ninja_task"
default_platform = "web"
out_dir = "dist"
asset_dir = "assets"

[web.app]
title = "Web Client | Ninja Task"

[web.watcher]
reload_html = true
watch_path = ["src", "assets"]

[web.resource]
style = [
  "assets/main.css"
]

[web.resource.dev]
style = [
  "assets/main.css"
]
